export const QUESTIONS = [
  "Whom would you want as a dinner guest?",
  "Would you like to be famous? In what way?",
  "Do you rehearse before making a telephone call? Why?",
  "What would make a perfect day for you?",
  "When did you last sing to yourself? To someone else?",
  "Would you rather keep the mind or body of a 30-year-old?",
  "Do you have a secret hunch about how you will die?",
  "Name three things you and your partner have in common.",
  "For what in your life do you feel most grateful?",
  "What would you change about the way you were raised?",
  "Tell your life story in as much detail as possible.",
  "What quality or ability would you want to wake up with?",
  "What truth would you ask a crystal ball to reveal?",
  "What have you dreamed of doing for a long time?",
  "What is the greatest accomplishment of your life?",
  "What do you value most in a friendship?",
  "What is your most treasured memory?",
  "What is your most terrible memory?",
  "If you had one year to live, what would you change?",
  "What does friendship mean to you?",
  "What roles do love and affection play in your life?",
  "Share five positive characteristics of your partner.",
  "How close and warm is your family?",
  "How do you feel about your relationship with your mother?",
  "Make three true we statements.",
  "I wish I had someone with whom I could share...",
  "What should a close friend know about you?",
  "Tell your partner what you honestly like about them.",
  "Share an embarrassing moment in your life.",
  "When did you last cry in front of another person?",
  "Tell your partner something you already like about them.",
  "What, if anything, is too serious to joke about?",
  "What would you regret not having told someone?",
  "What one item would you save from a burning house?",
  "Whose death in your family would disturb you most?",
  "Share a personal problem and ask for advice.",
];
