export const QUESTIONS = [
  "What is something about you that people usually notice too late?",
  "What kind of person makes you feel instantly safe?",
  'When do you feel most respected without anyone saying the word "respect"?',
  "What part of you do people often misunderstand because they only see the surface?",
  "What is a small detail that reveals a lot about who you are?",
  "What do you quietly admire in others because you wish you allowed yourself more of it?",
  "What kind of attention makes you open up instead of shut down?",
  "When was the last time you felt genuinely seen?",
  "What do you wish someone would ask you, but no one ever does?",
  "What is something you care about more than you usually admit?",
  "What kind of beauty makes you stop thinking for a moment?",
  "What memory still feels strangely alive inside you?",
  "What do you protect in yourself even when no one knows you are protecting it?",
  "What kind of people make you become softer?",
  "What kind of people make you become sharper?",
  "What is something you learned to hide because it made others uncomfortable?",
  "What do you reveal only when you trust someone?",
  "What makes you feel emotionally at home?",
  "What is a quality in yourself that you had to fight to keep?",
  "What kind of silence feels peaceful to you?",
  "What kind of silence feels dangerous to you?",
  "What is one thing you know about yourself that most people would not guess?",
  "What kind of loyalty means the most to you?",
  "What do you find difficult to forgive in others because it touches something personal in you?",
  "What do you forgive too easily?",
  "What is a part of you that became strong because it had no other choice?",
  "When do you feel most powerful without needing to prove anything?",
  "What kind of love makes you feel free rather than owned?",
  "What kind of care actually reaches you?",
  "What do you need from people when you are not at your best?",
  "What do you usually do when you feel emotionally exposed?",
  "What do you wish people understood about your distance?",
  "What do you wish people understood about your intensity?",
  "What kind of compliment reaches deeper than appearance or achievement?",
  "What do you want to be known for by the people who truly matter?",
  "What is something you are still becoming?",
  "What version of yourself do you miss, even if you could never return to it?",
  "What version of yourself are you proud you survived?",
  "What are you more sensitive to than you pretend to be?",
  "What do you notice about people that they rarely notice about themselves?",
  "What kind of conversation makes you lose track of time?",
  "What kind of person earns your honesty?",
  "What makes you feel chosen, not just liked?",
  "What do you need to feel before you can trust someone?",
  "What is one thing you would never want to become?",
  "What do you hope has not disappeared from you?",
  "What do you want to be brave enough to choose?",
  "What would your life look like if it was built around your real nature, not your adaptations?",
  "What do you think your soul has been trying to teach you for years?",
  "What part of you is waiting for permission to exist fully?",
];
